source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
# ignore all warnings from all pods
inhibit_all_warnings!

target "YOU" do
    #pod 'JSQMessagesViewController'
#pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
#pod 'CTAssetsPickerController',  '~> 3.3.0'

	pod 'MWPhotoBrowser'

	pod 'SAMKeychain'

	pod 'MLBPasswordTextField'

	pod 'SDWebImage', '~>3.8'

	pod 'FCFileManager'

	pod 'JKCategories'

	pod 'FMDB'

	pod 'FMDBMigrationManager'
    pod 'PureLayout'
    pod 'MJExtension'
    pod 'XLForm', '~> 3.0'
    pod 'DZNPhotoPickerController'
    pod 'BKPasscodeView', '~> 0.1.2'
    pod 'FDFullscreenPopGesture', '1.1'

end
